{% set name = "fake" %}
{% set version = "6.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fsprojects/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 6a1c8e9f21a8fcec0525e349882a8937e230d7539dbcf1475a40fca8817010ab

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - fake-cli --help

about:
  home: https://fake.build
  license: Apache-2.0
  license_file:
    - License.txt
    - license-files/
  summary: FAKE - F# Make
  dev_url: https://github.com/fsprojects/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
