{% set name = "fake" %}
{% set version = "6.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fsprojects/{{ name }}/archive/{{ version }}.tar.gz
  sha256: effb37116f5c5a110e86a4f0fb2a4b8252d30967c85280361b5e5b22ce0945ed

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - fake-cli --help

about:
  home: https://fake.build
  license: Apache-2.0
  license_file:
    - License.txt
    - license-files/
  summary: FAKE - F# Make
  dev_url: https://github.com/fsprojects/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
