{% set name = "fake" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fsprojects/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 12bf53cbfba05c9bc8d2493926da7c064807f18121f8d783d1a53709d86ba868

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - fake-cli --help

about:
  home: https://fake.build
  license: Apache-2.0
  license_file:
    - License.txt
    - license-files/
  summary: FAKE - F# Make
  dev_url: https://github.com/fsprojects/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
