{% set name = "fake" %}
{% set version = "6.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fsprojects/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 303052d48edb00dde27d381d81dae6c6b5771aa9ab341a36b5eec268681f5321

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - fake-cli --help

about:
  home: https://fake.build
  license: Apache-2.0
  license_file:
    - License.txt
    - license-files/
  summary: FAKE - F# Make
  dev_url: https://github.com/fsprojects/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
