context:
  version: 6.1.3

package:
  name: fake
  version: ${{ version }}

source:
  url: https://github.com/fsprojects/fake/archive/${{ version }}.tar.gz
  sha256: 303052d48edb00dde27d381d81dae6c6b5771aa9ab341a36b5eec268681f5321

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - fake-cli --help

about:
  license: Apache-2.0
  license_file:
    - License.txt
    - license-files/
  summary: FAKE - F# Make
  homepage: https://fake.build
  repository: https://github.com/fsprojects/fake

extra:
  recipe-maintainers:
    - danielnachun
